version: "3.3"

services:
  db:
    image: mysql/mysql-server:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: ubuntu:latest
    restart: on-failure
    volumes:
      - './:/var/www'
    ports:
      - 8000:80
    env_file:
      - .env

volumes:
    db_data: {}